### ISSUE TITLE
Benefits checker prototype flow in figma

### ISSUE THREAD

**Issue by adamgparsons** [citizensadvice/cads#86]

**Comment by adam-parsons-ca** [comment]
Here are the screens for the benefits checker prototype. Figma file can be found [here](https://www.figma.com/file/FpoQ4WIoCxEhzX5HxsYVJrKR/Benefit-checker-prototype?node-id=0%3A1)

![screen 1](https://user-images.githubusercontent.com/42031580/49444024-dc36d880-f7c5-11e8-8e68-0b5b1b9ce5ab.png)
![screen 2](https://user-images.githubusercontent.com/42031580/49444025-dc36d880-f7c5-11e8-9288-9dacdd95c0c9.png)
![screen 3](https://user-images.githubusercontent.com/42031580/49444027-dc36d880-f7c5-11e8-8cf1-4bbb2c7e90ed.png)
![screen 4](https://user-images.githubusercontent.com/42031580/49444028-dc36d880-f7c5-11e8-8b12-8304bab53a5e.png)
